// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/azure-anthropic-foundry.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const AZURE_ANTHROPIC_FOUNDRY_MODELS: ModelCatalog<typeof values, "azure-anthropic-foundry"> =
	flattenModelCatalog("azure-anthropic-foundry", values);
